// src/services/booksData.js
export const booksData = [
  {
    id: 1,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Classic',
    rating: 4.7,
    description: 'A novel set in the Jazz Age...',
    publication_year: 1925,
  },
  {
    id: 2,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Fiction',
    rating: 4.8,
    description: "A timeless novel of a child's moral awakening...",
    publication_year: 1960,
  },
  {
    id: 3,
    title: '1984',
    author: 'George Orwell',
    genre: 'Dystopian',
    rating: 4.6,
    description: 'A dystopian social science fiction novel...',
    publication_year: 1949,
  },
  {
    id: 4,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Romance',
    rating: 4.9,
    description: 'A romantic novel that...',
    publication_year: 1813,
  },
  {
    id: 5,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'Fiction',
    rating: 4.3,
    description: 'A story about a young boy’s journey...',
    publication_year: 1951,
  },
]
